language: rust
cache: cargo
sudo: false

rust:
  - nightly
  - beta
  - stable

before_script:
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - rustup component add rustfmt-preview

script:
  - if [[ $(rustup show active-toolchain) == stable* ]]; then cargo fmt --all -- --check; fi;
  - cargo build -p pb-rs -p quick-protobuf
  - ./run_test.sh
  - cargo test -p pb-rs -p quick-protobuf
  - if [[ $(rustup show active-toolchain) == nightly* ]]; then cargo bench -p quick-protobuf; fi;
