environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup install nightly
  - rustc -V
  - cargo -V

build: false

test_script:
  - cd tests/rust_protobuf
  - ./generate.sh
  - cargo build
  - cargo test
  - cd ../../examples/codegen
  - ./generate_module.sh
